---
title: Blog 1
author: Peimin Lin
date: '2020-08-28'
slug: blog-1
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2020-09-02T19:27:06+10:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE, 
  message = FALSE,
  warning = FALSE, 
  fig.align = "center", 
  fig.path = "figures/"
)
library(tibble)
library(timevis)
library(tidyverse)
library(broom)
library(MASS) # needed for rlm
library(lubridate)
library(zoo)
library(coronavirus)
library(widgetframe)
```

```{r read_data}
case <- read_csv("COVID19BE_CASES_AGESEX.csv")
mort <- read_csv("COVID19BE_MORT.csv")
data("coronavirus")
```

```{r case_tidy}
tidy_case <- case %>% mutate(MONTH = month(DATE),
                             YEAR = year(DATE)) %>% 
 count(MONTH,YEAR, name = "NUMBER")%>%
  drop_na( MONTH) 
```

```{r tibble}
tibble <- within(tidy_case, Date <- sprintf("%d-%02d", YEAR, MONTH)) %>% mutate(start = Date, end = NA)
```

```{r active, fig.cap = "Cases confrimed in Belgium since March 2020"}
active <- tibble %>%
  dplyr::select( NUMBER, start, end) %>% 
  rename(content = NUMBER)
timevis(active, showZoom = FALSE, height = "150px")
   
```

```{r mort}
tidy_mort <- mort %>% mutate(MONTH = month(DATE)) %>% 
 count(MONTH,REGION, AGEGROUP,name = "NUMBER") %>%
  drop_na(AGEGROUP)
```

```{r facet, fig.height = 8, fig.cap = "Difference age groups of death cases in three reigions" }
death <- ggplot(tidy_mort,
       aes(x= MONTH, y = NUMBER, fill = REGION)) +
  geom_col(position = "dodge") +
  facet_wrap(REGION~AGEGROUP,nrow = 3)
death
```

```{r second}
second <- coronavirus %>% 
  filter(date>= "2020-03-01") %>%
  dplyr::select(country, type, cases, date) %>%
  mutate(month = month(date))%>%
  group_by(country, type, month) %>%
  summarise(total_cases = sum(cases)) %>%
  pivot_wider(names_from = type,
              values_from = total_cases)%>%
  mutate(death_rate = death/confirmed*100)%>%
  mutate_if(is.numeric, round, digits = 2) %>%
  filter(country %in% c("US","China","Belgium"))

```

```{r dt, fig.cap = "date compared", width="100%",height = "600px" }
dtable <- DT::datatable(second, options = list(pageLength = 4))
dtable
```


```{r format, fig.cap = "the hardest time in Belgium"}
library(formattable)
format <- case %>% 
  mutate(MONTH = month(DATE)) %>%
 count(MONTH,REGION,PROVINCE, AGEGROUP,name = "NUMBER") %>%
  drop_na(PROVINCE, REGION,AGEGROUP)%>% 
  arrange(desc(NUMBER)) %>%
  head(10) %>%
as.data.frame() %>%
rownames_to_column("Variables") %>%
formattable(list(area(col = 2:6) ~ color_tile("#F5B7B1", "#7DCEA0")))
format
```
